server:
  # 端口号
  port: 8910

spring:
  # 应用名称
  application:
    name: service-sms
  # 环境设置: dev、test、prod
  profiles:
    active: dev
  # 数据源
  datasource:
    # 主库数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.167.87:23306/yygh_user?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  # 配置返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # nacos服务地址
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: 858556d4-ff55-44da-964e-fa7cd70fa16b
        group: yygh
      # 服务注册地址
      #        server-addr: 127.0.0.1:8848
      config:
        # 配置中心地址
        #        server-addr: 127.0.0.1:8848
        # 配置文件格式
        file-extension: yml
        # 命名空间
        namespace: 858556d4-ff55-44da-964e-fa7cd70fa16b
        # 分组
        group: yygh

  ## 配置mybatis-plus
  data:
    redis:
      database: 0
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      # password:
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
mybatis-plus:
  #  # 配置文件映射
  #  config-location: classpath*:**/mapper/*.xml
  # xml映射文件地址
  mapper-locations: classpath*:**/xml/*.xml

tencent:
  sms:
    phoneNumberSet:
      - 15269095903
    # 短信 SdkAppId
    smsSdkAppId: 1400943415
    # 模板ID
    templateId: 1946307
    # 短信签名内容 可选
    signName: 二进制BOX公众号
    codeTime: 10
    secretId: AKIDWvQ9lR8g7Rn11qjQuCH8nESSKzRfgV7W
    secretKey: GKBtOeiZCeuwlMkwra8VhgS2RfjbIo9J