server:
  # 端口号
  port: 9000
spring:
  # 应用名称
  application:
    name: service-gateway
    # 环境设置: dev、test、prod
  profiles:
    active: dev
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 858556d4-ff55-44da-964e-fa7cd70fa16b
    # alibaba在2020版之后不使用ribbon,这里使用loadbalancer代替,在配置文件中禁用ribbon
    loadbalander:
      ribbon:
        enable: false
    # 使用服务发现路由
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 设置路由id
        - id: service-hosp
          # 设置路由uri
          uri: lb://service-hosp
          # 设置路由断言，代理servicerId为auth-service的/auth/路径
          predicates:
            - Path=/*/hosp/**
        # 设置路由id
        - id: service-cmn
          # 设置路由uri
          uri: lb://service-cmn
          # 设置路由断言，代理servicerId为auth-service的/auth/路径
          predicates:
            - Path=/*/cmn/**